ingress:
  enabled: true
  path: "/api/"
service:
  enabled: true
  name: backend
  externalPort: 3100
  internalPort: 3100
livenessProbe:
  enabled: false
  path: "/status"
readinessProbe:
  enabled: false
  path: "/status"
application:
  track: stable
  tier: backend
  part: backend
  migrateCommand: []



customResources:
  - service-psql-nodeport:
    apiVersion: v1
    kind: Service
    metadata:
      name: dashboard-back-nest-postgresql-custom
      labels:
        app: postgresql
      annotations:        
    spec:
      ports:
      - name: tcp-postgresql
        nodePort: 30543  
        port: 5432
        protocol: TCP
        targetPort: tcp-postgresql
      selector:
        app: postgresql
        release: dashboard-back-nest-postgresql
        role: master
      sessionAffinity: None
      type: NodePort

  - service-back-nodeport:
    apiVersion: v1
    kind: Service
    metadata:
      name: dashboard-back-nest-custom
      labels:
        app: backend
      annotations:        
    spec:
      ports:
      - name: backend
        nodePort: 30310
        port: 3100
        protocol: TCP
        targetPort: 3100
      selector:
        app: dashboard-back-nest
        tier: backend
        track: stable
      sessionAffinity: None
      type: NodePort
